### ISSUE TITLE
MinerIncompatible with dub mint menu

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#1]
Miner are Incompatible with dub mint menu.
your own version work just fine, but it throw a null error in console and wont show bill.

in NR_auto. miner it works with Dubs Mint menu

**Comment by nullre** [comment]
Does Dubs Mint Menus have special treatment for PRF?

    string fullName = Find.Selector.SingleSelectedThing.GetType().FullName;
    if (fullName == null || !HarmonyPatches.ProjectRimFactory || !fullName.Contains("ProjectRimFactory"))
    {
        return;
    }

There is such processing in Dubs Mint Menus.  Do something only for PRF.
Therefore, it seems that an error occurs.
For now, fix it so that no error occurs.

**Comment by zymex22** [comment]
works
