### ISSUE TITLE
Smoke  on miner

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#11]
Can  smoke  effect be turned off in xml? or  can  it  be added to do so.?
my  t3  miner dosent need smoke.
but my t1 might.

**Comment by nullre** [comment]
I made it possible to set the workingEffect of miner.

https://github.com/nullre/Project-RimFactory-Revived/blob/fix_%2311/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L218
If you set EffecterDefName, the Effecter will be displayed.
Comment out if you don't want to display anything. Like now.

**Comment by zymex22** [comment]
Seems good you can merge and close
