### ISSUE TITLE
Miner def name

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#12]
I  cant change def name on miner in xml/def, if i do bill option list no resource bills.

**Comment by nullre** [comment]
miner is dynamically generating recipes.
miner is processing to add to recipes of "Building_AutoMachineTool_Miner".
https://github.com/nullre/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/AutoMachineTool/Building_MIner.cs#L197
please change it here too.

**Comment by zymex22** [comment]
okay understand =)
