### ISSUE TITLE
Slaughter

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#17]
when setting to max range its flickering red 2 places on zone like it cant be placed or something.
always same pattern like this

<img width="760" alt="slaughter" src="https://user-images.githubusercontent.com/41029070/79080159-bacbf200-7d13-11ea-95a0-1ef92940faf4.png">

**Comment by nullre** [comment]
Occurs for debug builds.
For performance, Slaughter does not check all ranges at once.
If the area is large, Slaughter scan the area dividedly.
In case of debug build,  the divided scan area is displayed.

please set release build in vs2019. and build.
use Source\Assemblies\ProjectRimFactory.dll.

**Comment by zymex22** [comment]
okay i try thanks =)
