### ISSUE TITLE
Puller update

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#18]
On PRF puller

Can it be made so it will not push out / take in, when Output cell is full (if not connected to stockpile)
Like on my Assemblers from PRF are saying “waiting to place products/items” when output cell are full. 

That would be usefull on puller too, so if not connected to a stockpile it will not spill over to other cell but just stop pulling until output cell are free again.
(usefull to connect to other mods like Replimat) where one cell need to be filled, but can’t make a stockpile under it

**Comment by zymex22** [comment]
alternatively it could stack more items in same slot like PRF storage does, so they dont spill out to other cells.

**Comment by nullre** [comment]
implemented in fix_#18_#20 branch. please check it out.
