### ISSUE TITLE
Copy/paste option on Puller

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#19]
Cant seem to get same copy / paste options as other storage building has like IR rollers or stockpiles

<img width="848" alt="options" src="https://user-images.githubusercontent.com/41029070/79464854-e93f1b00-7ffa-11ea-817c-dc6304184abf.png">

**Comment by nullre** [comment]
Puller's setting is filter settings.
The target of copy and paste is storage settings.
Storage setting is filter setting + priority setting.
Priority is not required for pullers, so pullers does not have priority settings.
Therefore, priority setting is not target to copy and paste.

implemented in fix_#19 branch.

**Comment by zymex22** [comment]
this works perfectly can merge
