### ISSUE TITLE
Puller Bug

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#20]
Related to #18.

If targeted stockpile is full it will just spill over to nearby cells instead stop pulling.

**Comment by nullre** [comment]
implemented in fix_#18_#20 branch. please check it out.

**Comment by zymex22** [comment]
Seem to be working just fine for both #18 and #20 no overflow.

but might be a new problem, when holding on to 1 item and say pending, i a stockpile have 
all slot full of silver, but one slot are 1 gold.
and it holding (pending) silver.
- it will not take in gold on input, event that storage isnt full
(will have an effect on roller conveyor setups)

can it be made so it does not take in/hold an item, and instead just say waiting for placement/items in input.
so if a gold come it would still be able to fill that stack that isnt full yet?

see picture for example with ploom and coconuts instead
<img width="1076" alt="Unavngivet" src="https://user-images.githubusercontent.com/41029070/79561093-07fbeb00-80a9-11ea-8fac-ecd6822a5385.png">

<img width="352" alt="21312" src="https://user-images.githubusercontent.com/41029070/79561303-6aed8200-80a9-11ea-8cd6-1d88907dca4c.png">

**Comment by nullre** [comment]
congifurable force placement.
https://github.com/nullre/Project-RimFactory-Revived/blob/fix_%2318_%2320/Defs/ThingDefs_Buildings/Buildings_AutoMachineTool.xml#L59-L61
