### ISSUE TITLE
Puller option

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#21]
Puller request to limitation tab:
Got a request, i dont know if it can be done?

-can a button to toggle item/stack count instead of only be able to count items?

<img width="517" alt="puller" src="https://user-images.githubusercontent.com/41029070/79467501-1e00a180-7ffe-11ea-8286-79c03e2a8355.png">

**Comment by nullre** [comment]
implemented in fix_#21 branch.

**Comment by zymex22** [comment]
it kinda work.
if doing full stacks, but if only do small stack when starting to place stack 2 it will stop after 1. pull.
no matter amount because second stack count as a stack even though its not full yet.

can it count full stacks only instead of just stacks?
