### ISSUE TITLE
In output cell color

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#22]
Can cell color be changed to match rest of PRF mod?

- Yellow for output cell.
- White for input cell(s)

**Comment by nullre** [comment]
The color setting can with XML.

![color1](https://user-images.githubusercontent.com/29091845/79573826-2c33e800-80fa-11ea-9fcb-36d5086c1c93.png)
https://github.com/nullre/Project-RimFactory-Revived/blob/fix_%2322/Defs/ThingDefs_Buildings/Buildings_AutoMachineTool.xml#L58-L65

![color2](https://user-images.githubusercontent.com/29091845/79573930-571e3c00-80fa-11ea-99fb-4a8b11f0cbaa.png)
![color3](https://user-images.githubusercontent.com/29091845/79573932-59809600-80fa-11ea-9054-963fc64df9f7.png)
https://github.com/nullre/Project-RimFactory-Revived/blob/fix_%2322/Defs/ThingDefs_Buildings/Buildings_AnimalStations.xml#L352-L357

**Comment by zymex22** [comment]
thats working perfectly thanks like that you made it an extension.
can merge
