### ISSUE TITLE
Chunk bug

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#23]
For some reason PRF started to count all stone chunks on map as colony wealth, so first raids will get super hard to survive.

some users said it might be new miner that does it, but coundt find where in code.
it was not present at version before we updated it.

**Comment by nullre** [comment]
case of calculate the wealth value of something that has no Market Value set,
It seems to be calculated from the workAmount of the recipe.

Miner is creating a recipe for mining stone chunks.
It seems that the wealth value of the stone chunk is calculated from the recipe's workAmount.

- Market Value is not set
- the count of production is 1 (Chunk)
- ThingDef which is the mining target of Miner

I Changed to set MarketValue of Def satisfying these conditions to 0.

**Comment by zymex22** [comment]
it works =)
