### ISSUE TITLE
sprinkler comp

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#24]
https://github.com/nullre/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/CultivatorTools/Building_Sprinkler.cs
could you make a comp/extension for this? 

a comp to set
Tickrate line 8
Grow rate line 16

**Comment by nullre** [comment]
implemented in fix_#24 branch.
https://github.com/nullre/Project-RimFactory-Revived/blob/fix_%2324/Defs/ThingDefs_Buildings/Buildings_Cultivators.xml#L271-L274
