### ISSUE TITLE
Puller Request

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#25]
Would it be posible make a new NR puller that can function 90degrees like picture below
and either a button to swap from left/right type or just 2 items one go to left and one go to right.

It should be a new puller not just update old one, as it will need new texture to it.

<img width="348" alt="pullerr" src="https://user-images.githubusercontent.com/41029070/79978746-b08ebe00-84a0-11ea-88ac-0a3cf3115c13.png">

Second version or swap by button
<img width="348" alt="pullerr" src="https://user-images.githubusercontent.com/41029070/79978962-11b69180-84a1-11ea-9c58-26c598ad9296.png">

**Comment by nullre** [comment]
Does the second version require switching the texture depending on the output destination?
If puller need to switch texture, can I add the output switching function (change textures) to the old puller?

**Comment by zymex22** [comment]
-a new puller called 90 degree puller.
-switching from left/right output (can swap texture or just flip texture)

and old one will just stay the same straight thrugh puller

**Comment by nullre** [comment]
implemented in fix_#25 branch.

**Comment by zymex22** [comment]
works fine (function) but might need arrow hidden or point at output cell not straight =)

![unknown](https://user-images.githubusercontent.com/41029070/80219150-647b7f00-8642-11ea-9ac1-49225864d705.png)

**Comment by nullre** [comment]
sorry, I fixed it. it is a misspelling.
https://github.com/nullre/Project-RimFactory-Revived/commit/d8ccfe509303ee8d287798c12fa22e23a32f3fca

If there is ```<li>ProjectRimFactory.AutoMachineTool.PlaceWorker_Arrow</li>```, an arrow will be displayed.
Therefore, I planned to erase it with inherit.

**Comment by zymex22** [comment]
yes this work can close and PR
