### ISSUE TITLE
Mint menu

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#26]
Did you find a better way to do mint menu?
i get some complaints about not working on mints (not show pretty buttons)

i see mod "Omni Core Drill" https://steamcommunity.com/sharedfiles/filedetails/?id=1089876213
working fine with mint menu, and its almost same function with bills.

i attached picture of omni drill and prf / nr drill with mint menu installed

<img width="632" alt="omni" src="https://user-images.githubusercontent.com/41029070/80068738-66f5b000-8540-11ea-80b5-c3ba6c188a6a.png">

<img width="711" alt="prf" src="https://user-images.githubusercontent.com/41029070/80068741-68bf7380-8540-11ea-83e3-3850244f90b5.png">

**Comment by nullre** [comment]
implemented in fix_#26 branch.

**Comment by zymex22** [comment]
yes working can merge
