### ISSUE TITLE
Roller Question

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#27]
On Rollers, is it possible to take off items with a Puller?
i see it cant as is now unless its on the end of a roller.

setup of what i mean.
if i change to Industrial roller that setup would work, because items on top are selectable(forbidden too)

<img width="377" alt="roller" src="https://user-images.githubusercontent.com/41029070/80069597-e768e080-8541-11ea-92b7-1bb9974d7863.png">

**Comment by nullre** [comment]
Can do the same with the roller alone, so I didn't give the Puller the ability to pick up items from the Roller.
do you need it?

**Comment by zymex22** [comment]
yes add puller to be able to pull would be good too

**Comment by nullre** [comment]
implemented in fix_#27 branch.

**Comment by zymex22** [comment]
this works
would it be hard to make PRF machines input also work with rollers like pusher do?
so input slot on example assembler/smart cooker can take items too?
if to hard not important right now.

Can close and PR if too hard
![31219558 585_image](https://user-images.githubusercontent.com/41029070/80312365-266a9080-87e5-11ea-90e0-07a7fb047123.png)
