### ISSUE TITLE
Arrows on placement

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#28]
Can a Arrow on placement be used on Puller and maybe rollers?
Would make placement much easier.

think its just a icon overlay made in c# because no blueprint picture is used for it.
using vanilla Arrow.png (icon = TexUI.ArrowTex,)

Industrial Roller Puller
<img width="292" alt="puller1" src="https://user-images.githubusercontent.com/41029070/80071115-5ba48380-8544-11ea-83a2-edc9df428610.png">
Prf Puller
<img width="329" alt="puller2" src="https://user-images.githubusercontent.com/41029070/80071118-5cd5b080-8544-11ea-9a6c-84751470a814.png">

**Comment by nullre** [comment]
implemented in fix_#28 branch.

**Comment by zymex22** [comment]
works super, can merge
