### ISSUE TITLE
Storage Update Impl

### ISSUE THREAD

**Issue by nullre** [nullre/Project-RimFactory-Revived#29]
- [x] when multi selec I/O set setting on all
- [x] Limit on cargo platform (ref #8)
- [x] When destroy delete items (option)
- [x] Hide items in storage (Deep Storage)
- [x] Forbid pawn to take out without I/O
- [x] output 1 item from cargo platform by storage tab

**Comment by nullre** [comment]
Please check once in this state.
implemented in test_#29 branch.

**Comment by zymex22** [comment]
<img width="787" alt="max stack" src="https://user-images.githubusercontent.com/41029070/80119306-d04de100-8589-11ea-9666-e4da9703d6bc.png">
max stack not showing like on crates, i will look how rest work, and write here

**Comment by nullre** [comment]
I made storage draw max stacks. I pushed test_#29 branch. please pull it.

**Comment by zymex22** [comment]
- no Rightclick are working.
- no rightclick with pawn draftet are working.
- Delete items on destroy working.
- limit work, just not show max limit on storage

Ideas:
- Maybe Output I/O port can use "Items" ITtab to see whats on connected/choosen cargo platform
and when clicking on that item extract somehow?
- Can hide item just be same function as you use in your Underground roller?

**Comment by nullre** [comment]
Enabled to set behavior at the time of destruction.
https://github.com/nullre/Project-RimFactory-Revived/blob/test_%2329/Defs/ThingDefs_Buildings/Buildings_Storage.xml#L224

**Comment by zymex22** [comment]
-Detroy config works
-draw max stacks works

**Comment by zymex22** [comment]
Hide items when inside storage, see picture
<img width="706" alt="hide" src="https://user-images.githubusercontent.com/41029070/80152706-77e40700-85bc-11ea-81dc-94ab3eb5966f.png">

multi select, when selecting 2 or 3 I/O port would it be posible to set setting on all 3 at once?
<img width="584" alt="multi" src="https://user-images.githubusercontent.com/41029070/80152740-85998c80-85bc-11ea-836e-f95ac76a293a.png">

-since its harder to get a item out now a quick pullout option could be nice if need just one item or one special one like a weapon with a curtain stat.

-Another option could be add items tab to I/O ports and let them be able to output one item with rightclick like below picture
<img width="813" alt="output" src="https://user-images.githubusercontent.com/41029070/80152798-9c3fe380-85bc-11ea-8285-291d33cf0f0c.png">


##############################
-Also.
can disable pawns able to go under be a xml option too? if ppl want it like old time and not like that they cant just use their resources?

**Comment by zymex22** [comment]
<img width="960" alt="log" src="https://user-images.githubusercontent.com/41029070/80153624-35232e80-85be-11ea-829d-95ce74def1b7.png">

getting this error when trying to pull last stuff out of I/O port.
happens only with last "stack" every time, not first many stacks.
https://gist.github.com/7c954fd60618415be942bc9198b65c3e

<img width="631" alt="log2" src="https://user-images.githubusercontent.com/41029070/80153944-d14d3580-85be-11ea-80ae-9de22496c20a.png">

**Comment by nullre** [comment]
sorry. There was a bug that the list held internally and the list of placed items were not synchronized. I fixed it.

- Hide items
I think I let items does not draw. but I do not know how to check. Please tell me.
- multi select setting
I have also set output settings. is there a problem?
- output 1 item from cargo platform
I changed to output the target item from ITab items by right-click.
Currently it unconditionally spawn item in the south Cell.
Is it necessary to specify the output slot? If so, how is it set it up?
- XML settings of pawn access without I/O
I plan to be able to set with xml.

**Comment by zymex22** [comment]
- Haul error/bug seems to be fixed
- Hide items works (you could test by cut a hole in texture like i did in picture)
- multi select/set works
- xml ok =)
- Rightclick output works.
/1 Can it just have rotate output cell like all other prf machines?.
/2 i dont know if is posible? 
but can I/O port connected to "cargo platform 1" get that items ITab too and rightclick to output directly from "cargo platform 1" to that I/O port? 
or is that impossible/too hard to make
<img width="660" alt="tab2" src="https://user-images.githubusercontent.com/41029070/80194004-0b97f080-861a-11ea-98d6-bf9f348d835a.png">

**Comment by zymex22** [comment]
https://gist.github.com/97ae8a994af9f70d906b66b90c1419a3
When Try to reinstall or minimize this error will show up until all stacks are gone. and they dont seem to get filled over in new location

<img width="565" alt="mini" src="https://user-images.githubusercontent.com/41029070/80199527-bb249100-8621-11ea-9581-f4f7eb927103.png">

**Comment by zymex22** [comment]
getting this error when destroying now set comp to true.
and it dosent destroy after, it just stay on ground and continue to work.
https://gist.github.com/95185bfe085ab58d73d1c10fc740dca0

<img width="723" alt="destroy" src="https://user-images.githubusercontent.com/41029070/80202535-1193ce80-8626-11ea-972e-cfdcf1261369.png">

**Comment by zymex22** [comment]
my assemblies file, yea i know i have that arrow error, thats because i just used old folder (def)
and put your new version in

[ProjectRimFactory.zip](https://github.com/nullre/Project-RimFactory-Revived/files/4528315/ProjectRimFactory.zip)

**Comment by nullre** [comment]
sorry. I fixed it.
This implementation is like a feasibility study.
This implementation is ignored for performance and versatility and reliability.
Once the specifications are finalized, implement correctly and test.
Therefore, it may be better to do a detailed test after that.
but I am happy to receive bug reports.

> /1 Can it just have rotate output cell like all other prf machines?.

implemented it.

> /2 i dont know if is posible?
> but can I/O port connected to "cargo platform 1" get that items ITab too and rightclick to output  directly from "cargo platform 1" to that I/O port?
> or is that impossible/too hard to make

it it possible. but I/O Port don't have a name. what do display right click menu?
for now, current implementation is port with number and draw connected line.

![image](https://user-images.githubusercontent.com/29091845/80224390-96153a00-8684-11ea-947d-bcae8696f33e.png)

**Comment by zymex22** [comment]
/2 just if you click on I/O port you can already use storage, but can Items tab like Cargo platform be added, they dont need a name =)

**Comment by nullre** [comment]
I fix output I/O port.
please check.

**Comment by nullre** [comment]
Based on my research, It was easy to place near (not on top) than I had thought.
Therefore, put items near if items will back to cargo.

**Comment by zymex22** [comment]
i have 2 things left:
- Need to be able to disable that not going under in xml (some poeple are mad about it)
- When reinstall and destroyContainsItems>true.
can it just drop things on ground like when destroyContainsItems>false
- Also that from #33 about storage crate to hide things

**Comment by nullre** [comment]
please check.

hide items, forbid pawn access settings.
https://github.com/nullre/Project-RimFactory-Revived/blob/test_%2329/Defs/ThingDefs_Buildings/Buildings_Storage.xml#L286-L287

The Pawn Access button will only be visible if forbidPawnAccess is false.

**Comment by zymex22** [comment]
- I/O mode botton on I/O port have texture in storage folder IoIcon.png
- When rightclick an item like pants and click pawn name + force wear it will throw:
error "could not resolve symbol "1_labelShort" for String "Force wear {1_labelShort}"
but if try again it works.
https://gist.github.com/f00cfe19be9eed87b5e7889f74bf8de4
- If I/O output port at placed on right side of a input port it cant right click output.
No problem in other directions.
- Can rightclick be disabled when "allow pawn" button is on too? like when its off?
draft pawn, and rightclick on middle cell/stack so not popup big menu of items

<img width="514" alt="5435" src="https://user-images.githubusercontent.com/41029070/80406068-c7c81400-88c3-11ea-9b06-556f5d4bdde0.png">

<img width="869" alt="pawn" src="https://user-images.githubusercontent.com/41029070/80405220-a0bd1280-88c2-11ea-858f-51f178f0ec40.png">

**Comment by nullre** [comment]
> I/O mode botton on I/O port have texture in storage folder IoIcon.png

I could not find IoIcon.png
I changed I/O Mode button texture. but I copied IoIcon.png from dsu.png. please change it.

> When rightclick an item like pants and click pawn name + force wear it will throw:
error "could not resolve symbol "1_labelShort" for String "Force wear {1_labelShort}"
but if try again it works.

This is an existing problem, regardless of this issue. 
The same problem occurs not only with pants but also with meal.
I need to check everything, the scope of correction is wide, and I would like to make it another issue.
#37 

> If I/O output port at placed on right side of a input port it cant right click output.
> No problem in other directions.

It will be input immediately after output.
I fixed it so that it doesn't output on top of IOPort.

> Can rightclick be disabled when "allow pawn" button is on too? like when its off?
> draft pawn, and rightclick on middle cell/stack so not popup big menu of items

Menus was showing when Pawn can retrieve the item.
Changed so that it can be configured with XML.
https://github.com/nullre/Project-RimFactory-Revived/blob/test_%2329/Defs/ThingDefs_Buildings/Buildings_Storage.xml#L288

**Comment by zymex22** [comment]
seems to be working Can PR
