### ISSUE TITLE
Slaughter suggestion

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#3]
Would it be possible for Slaugter to mute "death popup" if killed by slaugter.
maybe as a check option in slaugterss own settings?

**Comment by nullre** [comment]
Changed to kill after setting slaughter for pawns. like normal slaughtering.
I think the notification is gone.
Is it better to be configurable?

**Comment by zymex22** [comment]
configable or just disable i dont care, just i dossent come with 10 popup when killing my chickens

**Comment by zymex22** [comment]
works
