### ISSUE TITLE
Update on Original Quarry / miner code

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#30]
if have time some time i could use following on original miner (tier 1 & tier 2 miner)

- [x] bonus yield (list ore/items/Defs) (exampple t1 = steel slag)
- [x] set % chance for bonus yield (exampple t1 = steel slag 10%)
- [x] exclude what can be mined (list) for ores (t1/ t2) like `<li>steel</li>`
- [x] Smoke effect while mining (like on t3)
- [x] Pulse glower from Assembler
- [x] maybe set % chance on specific ores (like on quarry mod)
so Steel = 0.5 (0.5% change to get get)
so easier to balance out rare ores

Tier 3 miner NR version:
- [x] exclude (list) ores
- [x] set % chance for bonus yield
- [x] Pulse glower from Assembler
- [x] bonus yield (will add random when mining other ores)
(so if steel are on bonus list it will sometimes mine Steel also if set to plasteel.)

**Comment by nullre** [comment]
implemented in test_#30 branch.
about exclude ore, bonus yield.
t1:
https://github.com/nullre/Project-RimFactory-Revived/blob/b5a5556ad59b9f61ec0a92a7413dde4b0a420c96/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L95-L117
t2:
https://github.com/nullre/Project-RimFactory-Revived/blob/b5a5556ad59b9f61ec0a92a7413dde4b0a420c96/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L185-L194
t3:
https://github.com/nullre/Project-RimFactory-Revived/blob/b5a5556ad59b9f61ec0a92a7413dde4b0a420c96/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L282-L291

effecter
t1:
https://github.com/nullre/Project-RimFactory-Revived/blob/b5a5556ad59b9f61ec0a92a7413dde4b0a420c96/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L87-L89
t2:
https://github.com/nullre/Project-RimFactory-Revived/blob/b5a5556ad59b9f61ec0a92a7413dde4b0a420c96/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L177-L179

GlowerPulse:
t1:
https://github.com/nullre/Project-RimFactory-Revived/blob/b5a5556ad59b9f61ec0a92a7413dde4b0a420c96/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L79-L86
t2:
https://github.com/nullre/Project-RimFactory-Revived/blob/b5a5556ad59b9f61ec0a92a7413dde4b0a420c96/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L169-L176
t3:
https://github.com/nullre/Project-RimFactory-Revived/blob/b5a5556ad59b9f61ec0a92a7413dde4b0a420c96/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L250-L257

**Comment by zymex22** [comment]
**T3** seem to be working good
- but could _"bonus"_ list output instead of set bill?
so if Bill set to mine Plasteel, and it will land on bonus chance that will only output a "InsectJelly" not both Plasteel AND a InsectJelly

**Comment by zymex22** [comment]
**T1/T2**
If i set something as bonus yield like steel or plasteel will there be 2 times chance to get it?
or will it just overwrite original % change to spawn that item/ore?

so if i want to set plasteel chance on T2 to 1% chance only, can i do:
```
 <li Class="ProjectRimFactory.Common.ModExtension_Miner"> 
   <excludeOres> 
     <li>Steel</li> 
   </excludeOres> 
   <bonusYields> 
     <Plasteel Chance="0.01" Count="15" /> 
   </bonusYields> 
   <multiBonus>false</multiBonus> 
 </li> 
```
or would this just make 1% chance more then there already is? or can i control overall chance for certain ores or only chance for bonus? =)

Note to changes?
- Same as T3 only output Either original list OR bonus, not both
- can bonus list adjust chance on original list? or only on bonus ores?
- else either make bonus list adjust original list also or a new list to adjust original ore list chance, i dont know how its determined now? 
(unless i can just exclude a ore from original list and put it on bonus list instead)

**Comment by zymex22** [comment]
**funny Deep Infestations**

also another thing i have no idea if fit here...
got some reports on my T1/T2 miners im using:
`<li Class="CompProperties_CreatesInfestations" />`
and poeple are saying there will be deep infestation even when power is off on them, i dont know why that is, since vanilla don't do that.

**Comment by nullre** [comment]
> If i set something as bonus yield like steel or plasteel will there be 2 times chance to get it?
> or will it just overwrite original % change to spawn that item/ore?

original % is not change.
After determining the ore to be output with the same probability as before, draw bonus chance.

> can bonus list adjust chance on original list? or only on bonus ores?

only bonus ore.

Current process flow is described below (t1/t2/t3 all).

1. Perform mining processing as before.
1. Mining process is completed.
1. Determine the ore to be output as before.
1. &#x2795;***Draw bonus chance lot.(Added by this issue.)***
1. Place mined ore.
1. &#x2795;***Place bonus ore if won bonus lot.  (Added by this issue.)***

change to fix Either original list OR bonus issue.

1. Perform mining processing as before.
1. Mining process is completed.
1. Determine the ore to be output as before.
1. &#x2795;***Draw bonus chance lot.(Added by this issue.)***
1. Place mined ore &#x2795;***if didn't win bonus (Add)***
1. &#x2795;***Place bonus ore if won bonus lot.  (Added by this issue.)***

So, the original ore probability has nothing to do with this issue.
Did I answer your question?

***

By the way, As you may already know, t1 / t2 Miner ore rate calculation.
Select one by weighting the list elements.

| def.building.isResourceRock | weight |
|----|----|
| false | 3 |
| true | rockDef.building.mineableScatterCommonality &times; rockDef.building.mineableScatterLumpSizeRange.Average &times; rockDef.building.mineableDropChance(default 1) |


| mineableThing | rockThing | weight | %(weight &times; 100 / total weight) | isResourceRock | mineableScatterCommonality &times; mineableScatterLumpSizeRange.Average &times; mineableDropChance = weight (3 if isResourceRock is false) |
|----|----|----:|----:|----|----|
| Steel | MineableSteel | **35** | **61.07669** | True | 1 &times; 35 &times; 1 = 35 |
| Silver | MineableSilver | **0.8** | **1.396039** | True | 0.1 &times; 8 &times; 1 = 0.8 |
| Gold | MineableGold | **0.35** | **0.6107669** | True | 0.07 &times; 5 &times; 1 = 0.35 |
| Uranium | MineableUranium | **1.08** | **1.884652** | True | 0.12 &times; 9 &times;  1 = 1.08 |
| Plasteel | MineablePlasteel | **0.25** | **0.4362621** | True | 0.05 &times; 5 &times; 1 = 0.25 |
| Jade | MineableJade | **0.325** | **0.5671407** | True | 0.065 &times; 5 &times; 1 = 0.325 |
| ComponentIndustrial | MineableComponentsIndustrial | **4.5** | **7.852718** | True | 1 &times;  4.5 &times; 1 = 4.5 |
| ChunkSandstone | Sandstone | **3** | **5.235145** | False | 0 &times; 30 &times; 0.25 = 0 (3) |
| ChunkGranite | Granite | **3** | **5.235145** | False | 0 &times; 30 &times; 0.25 = 0 (3) |
| ChunkLimestone | Limestone | **3** | **5.235145** | False | 0 &times; 30 &times; 0.25 = 0 (3) |
| ChunkSlate | Slate | **3** | **5.235145** | False | 0 &times; 30 &times; 0.25 = 0 (3) |
| ChunkMarble | Marble | **3** | **5.235145** | False | 0 &times; 30 &times; 0.25 = 0 (3) |

Override of weight or change weight formula is not hard. please add to Issue if you needed.

***

about `<li Class="CompProperties_CreatesInfestations" />`
Maybe you don't know, but this is vanilla Infestation judgment processing code. 

    public bool CanCreateInfestationNow
    {
        get
        {
            CompDeepDrill comp = this.parent.GetComp<CompDeepDrill>();
            return (comp == null || comp.UsedLastTick()) && !this.CantFireBecauseCreatedInfestationRecently && !this.CantFireBecauseSomethingElseCreatedInfestationRecently;
        }
    }

`CompDeepDrill comp = this.parent.GetComp<CompDeepDrill>();` and 
`(comp == null || comp.UsedLastTick())` are important.

can create infestation if CompDeepDrill is not set, or CompDeepDrill is used at last tick(CompDeepDrill is being used now).
Power on / off is not checked. CompDeepDrill cannot be added to miner.
So, Infestation occurs regardless of whether the power is on/off.

**Comment by zymex22** [comment]
- ok on infestation, that make sense it need CompDeepDrill to see if used.
tought it only check if it was powered or not, but make sense it need some information on if it being worked or not.

- oh there is already some balance in how they are giving thats good, didnt know.

- i think i used name "bonus" wrong because it was not meant to be a bonus to mining, just added ores/defs to what can be mined, therefor i need Either original yield OR bonus yield and not both. i think i wrote it wrong sorry.

so what bonus really should do is just add a chance to something else to be spawned like steelSlag or InsectJelly.

and on T3 it will then overwrite original Bill if the chance is met. so instead of get a Plasteel (bill) sometimes they will get a insect jelly instead  (1% chance)

**so process flow would be T1/T2**
- Check bonus ore types
- mine Either one of bonus OR original ores
- output either one of them.

OR

- Perform mining processing as before.
- Mining process is completed.
- Draw bonus chance
- if hit bonus chance Output bonus yield only
- else output a ore from original yield list

**T3** process flow
- Set bill (Plasteel).
- work on plasteel
- When work done check bonus chance
- If bonus chance are met output ONLY bonus ore (insectJelly)
- Else output bill select (Plasteel)

**Comment by zymex22** [comment]
What i need to make after is:
**T1**
- Exclude all higend ores
- Exclude steel
- Add SteelSlagChunk (same chance steel had)

**T2** 
- Exclude component + plasteel
- increase chance on steel abit (i can do that by add bonus ore steel too?)
- decrease chance on stone chunks (i can do that by exclude and add bonus?)


**T3** 
- Add 1% chance to get insect jelly
- Exclude component + plasteel

**Comment by nullre** [comment]
Maybe I understood.
I think, it seems like mining failure rate, and mining failure products (junk).
Since mining has failed, mining product is not produced, but a junk is produced.

Which of the following statements is true?

    <bonusYields> 
      <Steel Chance="0.3" Count="15" /> 
      <Plasteel Chance="0.3" Count="15" /> 
    </bonusYields>

A : Calculate each chance :
Actual Product Steel rate = (1 - (0.7 * 0.7)) / 2 = 0.255 = 25.5%

B : Treat Chance like Weight and calculate from the chance sum:
Actual Product Steel rate = (0.3 + 0.3) * 0.3 / (0.3 + 0.3) = 0.6 * 1 / 2 = 0.3 = 30%

C : Change the XML structure to specify total bonus chance and set weights individually.

    <bonusYields Chance="0.6">
      <Steel Weight="1" Count="15" /> 
      <Plasteel Weight="1" Count="15" /> 
    </bonusYields>

Actual Product Steel rate = 0.6 * 1 / (1 + 1) = 0.3 = 30%.

**Comment by zymex22** [comment]
For T3 yes thats right! :D junk is mined because of "failed mining" :D

For t1/t2
i dont know wich one above is best easiest for you? =)

but if i can edit chance on a specific ore if needed else normal chance.
And add more ores/junk to list/chance i'm happy =)

end goal is im going to do this:
What i need to make after is:
**T1**
- Exclude all higend ores
- Exclude steel
- Add SteelSlagChunk (same chance steel had)

**T2**
- Exclude component + plasteel
- increase chance on steel abit (i can do that by add bonus ore steel too?)
- decrease chance on stone chunks (i can do that by exclude and add bonus?)

**T3**
- Add 1% chance to get insect jelly instead of bill (Junk)
- Exclude component + plasteel

maybe more... but thats the idea on how i want to control it =)

**Comment by nullre** [comment]
t1:
https://github.com/nullre/Project-RimFactory-Revived/blob/ec4789c369d1c38366e595138e6071dc73116925/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L95-L114
t2:
https://github.com/nullre/Project-RimFactory-Revived/blob/ec4789c369d1c38366e595138e6071dc73116925/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L182-L198
t3:
https://github.com/nullre/Project-RimFactory-Revived/blob/ec4789c369d1c38366e595138e6071dc73116925/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L287-L295

t1/t2:
Added a button only for Debug Build.
![image](https://user-images.githubusercontent.com/29091845/81705270-d4469200-94a9-11ea-9730-1e6b5a8cebf0.png)

Output log when button is clicked.
Simulation log of 100000 times Minig.

![image](https://user-images.githubusercontent.com/29091845/81705458-0526c700-94aa-11ea-9a2f-4600d8d3cddf.png)

    number of trials : 100000
    def : ComponentIndustrial / stackCount : 2 / minedCount : 19670 / mine rate(%) : 19.67
    def : ChunkLimestone / stackCount : 1 / minedCount : 13225 / mine rate(%) : 13.225
    def : ChunkMarble / stackCount : 1 / minedCount : 13140 / mine rate(%) : 13.14
    def : ChunkSandstone / stackCount : 1 / minedCount : 13094 / mine rate(%) : 13.094
    def : ChunkSlate / stackCount : 1 / minedCount : 13013 / mine rate(%) : 13.013
    def : ChunkGranite / stackCount : 1 / minedCount : 12812 / mine rate(%) : 12.812
    def : Steel / stackCount : 20 / minedCount : 5090 / mine rate(%) : 5.09
    def : ChunkSlagSteel / stackCount : 1 / minedCount : 5075 / mine rate(%) : 5.075
    def : Silver / stackCount : 40 / minedCount : 3557 / mine rate(%) : 3.557
    def : Jade / stackCount : 40 / minedCount : 1324 / mine rate(%) : 1.324

**Comment by zymex22** [comment]
yes this seem to be perfect! just what i need to tweak and balance miners =)
if its done i can Close and you can PR? =)
