### ISSUE TITLE
Storage / IO freezer

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#31]
I tried making a patch for Rimfridge, to make a Cooled I/O port for food.
https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Patches/RimFridge.xml
But it didnt seem to work right, and think its because Rimfridge uses rare ticks and I/O uses normal.
if i set to normal, storage works fine but not cooling.
if i set to rare temperature works fine, but storage have some trouble need to swap around alot in settings to get it work ingame.

is there a work around for that? or would it be easier just make own freezer/cooler comp, and just set temp in xml so like IO Fridge port to -5 degress by a comp in xml 
This mod have made a comp like that and source is there maybe can get from there?:
https://github.com/emipa606/NPDTiers
![FridgeHopper_south](https://user-images.githubusercontent.com/41029070/80155108-41f55180-85c1-11ea-924b-4ed2630f42dc.png)

**Comment by nullre** [comment]
Maybe call TickRare() from Tick() can do it.
Like https://github.com/nullre/Project-RimFactory-Revived/commit/a036a712aaec9ccd74b19d86f6ef99d3936450e2

**Comment by zymex22** [comment]
yes that seems to solved problem now both temperature and I/O function normal =)

**Comment by zymex22** [comment]
can pr
