### ISSUE TITLE
Second layer comp see

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#32]
can i use this in my source to get second layer option? 
https://github.com/KiameV/rimworld-rimfridge/blob/master/Source/CompSecondLayer.cs

Its super usefull tool to have when doing xml and textures to be able to layer on top base texture =) use it in my gloomy vanilla overhaul mod too for kingbed is 2 textures.
i use Gloomy Furniture comp in there.

<img width="622" alt="22222" src="https://user-images.githubusercontent.com/41029070/80155668-79183280-85c2-11ea-9fa1-a0d04933adee.PNG">

**Comment by nullre** [comment]
Maybe yes you can. Did you try it?

**Comment by zymex22** [comment]
i did not i would ask you first if i could just use that CompSecondLayer.cs and compile to get it working or need to do something to get it in PRF =)
