### ISSUE TITLE
storage crate size

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#35]
I made a "Tiny steelCrate" 1x1 in my recent build, but just realized it dont work.
It can only hold 1 stack.

if i change to 2x1 or 2x2 it works just fine.
are there anything in crate c# that prevent 1x1 to work?.
I wasnt able to see in source if it was demanded somewhere to be 2x2 to work(original size)

**Comment by nullre** [comment]
The pawn carries the item to an empty Cell.
In the case of 2x2, the brought-in items are stacked in one cell.
Therefore, 3 cells are empty.
Pawns can be carried to 3 empty cells.

In the case of 1x1, empty cells cannot be created.
Therefore, the pawn cannot be carried.

in the case of PRF storage.
I think Deep Storage etc are doing other processing.

**Comment by zymex22** [comment]
ok i understand i will ask LWM from Deep storage how he did it =)
