### ISSUE TITLE
PRF mod setting menu

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#36]
can we try at some point see what Spdskatr mod setting menu was setup to work with, kinda wanna see what options he had in mind when i made it.

**Comment by nullre** [comment]
As far as I can see, it's almost not implemented.
Ported CultivatorTools\ModSettings.cs.
![image](https://user-images.githubusercontent.com/29091845/80479713-6b7bf780-898a-11ea-914c-cc59bfe03911.png)

**Comment by zymex22** [comment]
oh yea that wasnt much =) though it was more options :P
