### ISSUE TITLE
Right-click menu problem at item tab on Storage

### ISSUE THREAD

**Issue by nullre** [nullre/Project-RimFactory-Revived#37]
https://github.com/nullre/Project-RimFactory-Revived/issues/29#issuecomment-620144634

When rightclick an item like pants and click pawn name + force wear it will throw:
error "could not resolve symbol "1_labelShort" for String "Force wear {1_labelShort}"
but if try again it works.
https://gist.github.com/f00cfe19be9eed87b5e7889f74bf8de4

![image](https://user-images.githubusercontent.com/41029070/80405220-a0bd1280-88c2-11ea-858f-51f178f0ec40.png)

**Comment by nullre** [comment]
fixed in fix_#37 branch.

**Comment by zymex22** [comment]
yes seems to work can PR
