### ISSUE TITLE
cultivator bug

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#38]
Had a report where cultivator will not work when going over cables in ground.
it will not harvest that cell where cable are. only on that one using: Building_Cultivator.cs

**Comment by nullre** [comment]
fixed in fix_#38 branch.

**Comment by nullre** [comment]
I fixed the same cable issue.
I fixed warning of duplicate using directive.

**Comment by zymex22** [comment]
seems to work i have accept PR i close
