### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#4]
When i Compile your files i get no errors in compiler but Puller wont work in game just throw errors until cap when placing.

It work just fine if i use your made assemblies just can't compile my own and use.
see picture for what error et throw

<img width="987" alt="error" src="https://user-images.githubusercontent.com/41029070/78946618-8661f700-7ac3-11ea-86f9-06f4475caaa2.png">

**Comment by nullre** [comment]
Click on it and you will get a stack trace below.
I want to see it.
Also, I want the assembly you built and Buildings_AutoMachineTool.xml.

**Comment by zymex22** [comment]
my xml is here:

https://github.com/nullre/Project-RimFactory-Revived/issues/5

my compiled assemblies are here:

[ProjectRimFactory.zip](https://github.com/nullre/Project-RimFactory-Revived/files/4461332/ProjectRimFactory.zip)

**Comment by zymex22** [comment]
<img width="1026" alt="error2" src="https://user-images.githubusercontent.com/41029070/78988507-65d08600-7b31-11ea-9f42-1fc061d2d5d1.png">

https://gist.github.com/2bda75cfb236019abbf2dc32aa46a56a

**Comment by nullre** [comment]
Maybe a new pull will fix it.

**Comment by zymex22** [comment]
Works ill upload new project file to mine, your project file was wrong, no proble,
