### ISSUE TITLE
Assembler update

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#41]
Hello i had a Assembler update in mind wich would allow me to create more and better control over machines

A comp or extension to set following on each def assembler
- [x] Work speed factor
- [x] Skill level 1-20
- [x] Able to use smoke effect on working like NR miner
- [x] Swap from tex00 to texture 01 when working (true/false)
- [x] Glow comp that can pulse light like red lamp when working
- [x] Hide Idle/working text (true/false)

Less important
- [ ] Would it be possible to make recipe database range or global by comp
- [ ] Maybe able to turn on NR Speed/Power extension for machines?
- [ ] Set input range for Assemblers, maybe with NR Power/Range
- [ ] Let input take from PRF puller #34

**Comment by nullre** [comment]
I have a few questions to ask.

- Work speed factor

Originally there is workSpeedBaseFactor in AssemblerDefModExtension.
https://github.com/nullre/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/SAL3/Exposables/AssemblerDefModExtension.cs#L11
Can you use this?

- Skill level 1-20

Do you want to set the skill level uniformly? Individual?  

---
uniformly

    <skillLevel>15</skillLevel>

or individual

    <skillLevel>
      <Cooking>15</Cooking>
      <Crafting>8</Crafting>
    </skillLevel>
---

- Swap from tex00 to texture 01 when working (true/false)

Do you just want to switch textures?
Is "tex00 to texture 01" meaningful?

- Glow comp that can pulse light like red lamp when working

Does it just glow red when working? do pulse?
I don't know how pulse works.

- Hide Idle/working text (true/false)

with xml? ingame?

**Comment by zymex22** [comment]
- oh i didnt know didnt see it anywhere, but yes if i can set speed its perfect =)
- skill individually each machine since i use assembler class for different machines.
oh... you mean each skill.. i dont think i will need machines with diffents skills so can just have same level for all skils (1 machine)
- yes want to be able to use 2 textures with current one as first and a second one when working so i can use fire look on my new furnace when working. (if cant find 01 just use 1 texture only)
- glow was just if i could make blinking/pulsing light somehow so it can flash redlight when working, would look good on furnace.
- With xml is fine for hide.

**Comment by nullre** [comment]
thank you for your reply.

> oh i didnt know didnt see it anywhere, but yes if i can set speed its perfect =)

Maybe Assembler can work at double speed if you do the following.

    <modExtensions>
      <li Class="ProjectRimFactory.SAL3.Exposables.AssemblerDefModExtension">
        <importRecipesFrom>ElectricStove</importRecipesFrom>        
        <workSpeedBaseFactor>2</workSpeedBaseFactor>
      </li>
    </modExtensions> 

> glow was just if i could make blinking/pulsing light somehow so it can flash redlight when working, would look good on furnace.

I might not have understood that content correctly.
I will try it. please check after that.

**Comment by zymex22** [comment]
https://media.giphy.com/media/3o6fIPzkn0CsfSo0lG/giphy.gif
glower / pulse light like this picture =)
normal comp Glow can only light solid light.
would be nice if i could make it pulse

**Comment by zymex22** [comment]
just tested:
```
<modExtensions>
  <li Class="ProjectRimFactory.SAL3.Exposables.AssemblerDefModExtension">
    <importRecipesFrom>ElectricStove</importRecipesFrom>        <!-- import same bills as vanilla electric stove have -->
    <workSpeedBaseFactor>2</workSpeedBaseFactor>
  </li>
</modExtensions> 
```

That works thank didnt know it was aldready in =) i have marked done on original post

**Comment by nullre** [comment]
Change the glowColor and glowRadius of CompGlower little by little?
I'll try it.

**Comment by nullre** [comment]
> Able to use smoke effect on working like NR miner

Assembler use only Drill Effect instead of effectWorking of RecipeDef?
SelfCooker etc too?

**Comment by nullre** [comment]
effectWorking of ButcherCorpseFlesh Recipe is ButcherFlesh Effect.
![butcher_effect](https://user-images.githubusercontent.com/29091845/80726849-ec302480-8b3f-11ea-8c84-8e521f814607.gif)

effectWorking of CookMealSimple Recipe is Cook Effect.
![cook_effect](https://user-images.githubusercontent.com/29091845/80727299-7e382d00-8b40-11ea-82c6-87b33e9b26b5.gif)

These are when using the effectWorking of RecipeDef.

**Comment by nullre** [comment]
Implemented pulse temporarily.
is it right?

![pulse](https://user-images.githubusercontent.com/29091845/80735644-f6582000-8b4b-11ea-9d04-cae20aa2e7b9.gif)

XML:

      <li Class="ProjectRimFactory.Common.CompProperties_GlowerPulse">
        <minGlowRadius>3</minGlowRadius>
        <maxGlowRadius>5</maxGlowRadius>
        <minGlowColor>(255,0,0,100)</minGlowColor>
        <maxGlowColor>(255,0,0,10)</maxGlowColor>
        <intervalTicks>15</intervalTicks>
      </li>

It makes a linear transition during intervalTicks between max and min.

**Comment by zymex22** [comment]
![image](https://user-images.githubusercontent.com/29091845/80726849-ec302480-8b3f-11ea-8c84-8e521f814607.gif)
this looks really good

![image](https://user-images.githubusercontent.com/41029070/80742760-343d5000-8b1c-11ea-8db5-a85f95719bea.png)
this looks good too =)

**Comment by zymex22** [comment]
updated Original post

**Comment by nullre** [comment]
please check test_#41 branch.
Only SelfCooker is set.

- SkillLevel
https://github.com/nullre/Project-RimFactory-Revived/blob/66644eaaa2c1122093d789ea07f110e9707ebba2/Defs/ThingDefs_Buildings/Buildings_Assemblers.xml#L259
Recipes that do not meet the skillRequirements will be hidden.

- Able to use smoke effect on working like NR miner
The effectWorking of RecipeDef is used.

- Swap from tex00 to texture 01 when working (true/false)
https://github.com/nullre/Project-RimFactory-Revived/blob/0d56b563bce352663d584fa4c7f3ec71e5f12380/Defs/ThingDefs_Buildings/Buildings_Assemblers.xml#L260-L264

- Glow comp that can pulse light like red lamp when working
https://github.com/nullre/Project-RimFactory-Revived/blob/6ae43f42475a1b2e0fcfe18edc82f948793ab38d/Defs/ThingDefs_Buildings/Buildings_Assemblers.xml#L230-L239

- Hide Idle/working text (true/false)
https://github.com/nullre/Project-RimFactory-Revived/blob/66644eaaa2c1122093d789ea07f110e9707ebba2/Defs/ThingDefs_Buildings/Buildings_Assemblers.xml#L265

**Comment by zymex22** [comment]
- Able to use smoke effect on working like NR miner
The effectWorking of RecipeDef is used.
-- Can this be turned on/off didnt see it in def.
-- also can it overwrite RecipeDef effect if that item have wrong effectWorking 

- glower seems to work
- work texture work
- hide idle work
- set skill level work

**Comment by nullre** [comment]
added sound process. enabled to override effect and sound.
please check.

https://github.com/nullre/Project-RimFactory-Revived/blob/fa32bbdfabf417e5c92ba9fe9dedd8e55f956d81/Defs/ThingDefs_Buildings/Buildings_Assemblers.xml#L267-L281

**Comment by zymex22** [comment]
wrong at line 281. but i understand.

also it does work =) i check it on main list

**Comment by zymex22** [comment]
You are so fast and amazing at doing this, i didnt expect this be so quick and even better than i Imagineged it

**Comment by nullre** [comment]
The remaining four take time.
If you want to merge it into your repository first, you should make the rest a new Issue.
If not, I will do this issue slowly. Merge will be delayed.

**Comment by zymex22** [comment]
You can PR theese first theese seems most importent i move others to new issue
