### ISSUE TITLE
Drones

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#43]
I have  A bug/todo from Spdskatr original todo list:
- Make drones unforbid stuff after mining

for some reason drones forbid stuff after mined, can it be turned off? so they do not forbid anything

**Comment by nullre** [comment]
Which ThingDef is that?

**Comment by zymex22** [comment]
its in PRF - Drones.
but use same assemblies/drones as PRF - core

i think its:
<thingClass>ProjectRimFactory.Drones.Building_DroneStationRefuelable</thingClass>

https://github.com/zymex22/Project-RimFactory-Revived-drones/blob/master/Defs/ThingDefs_Buildings/Buildings_DroneStation.xml

**Comment by nullre** [comment]
fixed in fix_#43 branch.

**Comment by zymex22** [comment]
this works can PR and close
