### ISSUE TITLE
Assembler part 2

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#44]
Less important
- [x] Would it be possible to make recipe database range or global by comp
(Range for how long there can be betweem Recipe database and a assembler to see it, now its next cell to it.)
- [x] Maybe able to turn on NR Power/speed extension for machines?
(to boost speed in cost of power, if used on it, else just fixed power like now)
- [x] Set input range for Assemblers (materials), maybe with NR Power/Range
(or just with xml set range radius, right now 2 cell bigger then assembler used)
- [x] A 3. Texture swap for when no power (like IR uses)
1. No power
2. Power
3. Working (done)
- [x] Set artistic level seprate from other skills

**Comment by nullre** [comment]
I have questions.

> Would it be possible to make recipe database range or global by comp

Is range the distance between the recipe database and the adjacent  WorkTable?
Is range the distance between the assembler and the adjacent recipe database?
Both?

> Maybe able to turn on NR Speed/Power extension for machines?

use power setting? Boost power tab.

**Comment by zymex22** [comment]
- yes range for how long between DB and Assembler

- also Yes boos power tab so input range can be incresed at cost of power use like on NR Slaughter does

**Comment by zymex22** [comment]
updated original

**Comment by nullre** [comment]
UniversalAssembler - RecipeDatabase range.
https://github.com/nullre/Project-RimFactory-Revived/blob/56034adea7a995b062c85410b48ce95467ca047f/Defs/ThingDefs_Buildings/Buildings_Assemblers.xml#L95-L98

RecipeDatabase - WorkTable range.
https://github.com/nullre/Project-RimFactory-Revived/blob/56034adea7a995b062c85410b48ce95467ca047f/Defs/ThingDefs_Buildings/Buildings_Assemblers.xml#L193-L196

If you don't need it, delete the tag and it will return to its original behavior.

**Comment by zymex22** [comment]
I tested recipe range and it was working.
i mark as done.
i see what you mean about both import to recipe db and from db to assembler now =) 
didnt realize before but thats ok =)



sorry im late
been busy this weekend with my son and some xml update, i just uploaded all my work to master.
also LWM from deepstorage send me 3 fixes for some comments on steam about bugs.

**Comment by zymex22** [comment]
How is art set now? 
before it was set all skills at 10 except artistic right?
what are art set for 0 or same as rest of them?

could art maybe be a seprate skill to set in xml since some mod will scale if high art skill
so like this:
SkillLevel: 10 (all other skills)
ArtLevel: 5 (if not set 0)

**Comment by nullre** [comment]
All skill levels including art are set to XML SkillLevel.
Previously, all were set to 0 except for art. art was 10.

> Set artistic level seprate from other skills

OK.

    <skillLevel>20</skillLevel>
    <artSkillLevel>10</artSkillLevel>

**Comment by nullre** [comment]
added power setting comp.
I've made it Comp so that the current Building class is not modified as much as possible.

https://github.com/nullre/Project-RimFactory-Revived/blob/d30087931ba43553b69e96d1089072deb814f9e3/Defs/ThingDefs_Buildings/Buildings_Assemblers.xml#L248-L268
https://github.com/nullre/Project-RimFactory-Revived/blob/d30087931ba43553b69e96d1089072deb814f9e3/Defs/ThingDefs_Buildings/Buildings_Assemblers.xml#L270-L272

**Comment by nullre** [comment]
added PowerOff graphicData.
https://github.com/nullre/Project-RimFactory-Revived/blob/fef021fc151548cfe4b0655b7951347c9fea273b/Defs/ThingDefs_Buildings/Buildings_Assemblers.xml#L298-L302

**Comment by nullre** [comment]
added artSkillLevel.

https://github.com/nullre/Project-RimFactory-Revived/blob/b24c8b63439f282794f895f1f9a3c629d4017e62/Defs/ThingDefs_Buildings/Buildings_Assemblers.xml#L292-L293

I created a Sculpture with Assembler and checked the quality.

**Comment by zymex22** [comment]
- power for range seem to work
- Power for speed seem to work
- Off texture seem to work
- Art skill level seem to work

**Comment by zymex22** [comment]
Can close now and PR
