### ISSUE TITLE
assembler workerslot request (can wait)

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#45]
Hello nobo i have a question / request.

is it possible to add workslot to assemblers?
it would still be assembler that have skill and work like it does now.

so it will require a pawn to operate it, to count as workamount, like normal workbenches does.
maybe a set skill required to operate it, like 10 intellectual.
but assembler would still have skills for work being done still

kinda like here if that makes sense?
(worker slot from a vanilla workbench on a PRF assembler)
<img width="550" alt="workd" src="https://user-images.githubusercontent.com/41029070/80945405-09891b00-8dec-11ea-9905-99402fdf1e62.png">

**Comment by nullre** [comment]
I might not have understood that content correctly.
What's concretely wrong with the assembler?

**Comment by zymex22** [comment]
nothing wrong =)
i would ask if i can use worker slot to do work like one vanilla benches.

but still use assembler mechanics(skills)

* so a hybrid of vanilla workbench and PRF assembler =)

**Comment by nullre** [comment]
Possible, but the current Building Class cannot.
It may take some time as I need to make a new one.

**Comment by zymex22** [comment]
okay i could just be cool on some buildings in PRF - inanity and also in some of the early building to still require a pawn to operate it even though its still the machine/internal pawn that make the products =)
