### ISSUE TITLE
Mod settings

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#46]
Would it be possible make some options to PRF mod settings?
- Turn off PRF help button
- Overwrite Turn off `<drawStatus>`
- Overwrite Turn off `<doEffect>`
- Turn off Pulse glower comp effect
- Overrule Texture swap to only use main one (no off/working)

**Comment by nullre** [comment]
added Mod Setting.
Settings screen is constructed from Settings/Settings.xml.
https://github.com/nullre/Project-RimFactory-Revived/blob/169a75cb4b49ab9ccd5a57b2e1776230f76f51d0/Settings/Settings.xml

The items checked on the setting screen will be patched.
The patch process is described in Settings.xml.
Because it is a patch process, it is necessary to restart after setting.

**Comment by zymex22** [comment]
ill look at it soon i was forgetting use "code" in original post i have done it now for drawStatus and doEffect

dont know if you could see them before and added it or not =)

**Comment by nullre** [comment]
I haven't added them.
If you add the patch process to Settings.xml, it will be added to the setting screen.
Add the following to Settings.xml.

    
    <Row Class="ProjectRimFactory.Common.PatchItem">
      <key>turn.off.draw.status</key>
      <label>PRF.Settings.TurnOffDrawStatus.Label</label>
      <description>PRF.Settings.TurnOffDrawStatus.Desc</description>
      <Patch>
        <Operation Class="PatchOperationRemove">
          <success>Always</success>
          <xpath>/Defs/ThingDef/modExtensions/li[@Class="ProjectRimFactory.SAL3.Exposables.AssemblerDefModExtension"]/drawStatus</xpath>
        </Operation>
        <Operation Class="PatchOperationAdd">
          <success>Always</success>
          <xpath>/Defs/ThingDef/modExtensions/li[@Class="ProjectRimFactory.SAL3.Exposables.AssemblerDefModExtension"]</xpath>
          <value>
            <drawStatus>false</drawStatus>
          </value>
        </Operation>
      </Patch>
    </Row>

    
    <Row Class="ProjectRimFactory.Common.PatchItem">
      <key>turn.off.do.effect</key>
      <label>PRF.Settings.DoEffect.Label</label>
      <description>PRF.Settings.DoEffect.Desc</description>
      <Patch>
        <Operation Class="PatchOperationRemove">
          <success>Always</success>
          <xpath>/Defs/ThingDef/modExtensions/li[@Class="ProjectRimFactory.SAL3.Exposables.AssemblerDefModExtension"]/doEffect</xpath>
        </Operation>
        <Operation Class="PatchOperationAdd">
          <success>Always</success>
          <xpath>/Defs/ThingDef/modExtensions/li[@Class="ProjectRimFactory.SAL3.Exposables.AssemblerDefModExtension"]</xpath>
          <value>
            <doEffect>false</doEffect>
          </value>
        </Operation>
      </Patch>
    </Row>

**Comment by zymex22** [comment]
if i need a text on top saying all setting require restart instead of only on popup.
can i do that in XML or in C#?

**Comment by zymex22** [comment]
if can be done by XML you can close and PR =) because seem to work for what i need now =)

**Comment by nullre** [comment]
Do you want to display the text at the top of the settings screen? Then XML is possible.

https://github.com/nullre/Project-RimFactory-Revived/blob/8996fe58f08f76fe3abebf05a8a2dd874b1f494a/Settings/Settings.xml#L4-L13

Also, It seems that simple RichText can be used.
https://docs.unity3d.com/560/Documentation/Manual/StyledText.html
https://github.com/nullre/Project-RimFactory-Revived/blob/8996fe58f08f76fe3abebf05a8a2dd874b1f494a/Languages/English/Keyed/AllKeyed_Settings.xml#L6

![image](https://user-images.githubusercontent.com/29091845/81474462-92ff7980-9240-11ea-9260-62b9e6baa179.png)

**Comment by zymex22** [comment]
works perfect can PR and i will play with make it ready in xml =)

**Comment by nullre** [comment]
@zymex22 I added image row, container row, split row. I made pr after that. Please be careful, just in case.
