### ISSUE TITLE
Smart hopper pull from ground

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#47]
had a user asking if smart hopper could also pickup from ground instead of only if cells are inside a stockpile?, kinda like PRF puller are able to do.
Building_SmartHopper.cs

https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/SAL3/Things/Building_SmartHopper.cs

**Comment by nullre** [comment]
I might not have understood that content correctly.
Do you want SmartHopper to pick up from ground as well as a Stockpile?

**Comment by zymex22** [comment]
<img width="509" alt="pickup" src="https://user-images.githubusercontent.com/41029070/81466911-6b26fc00-91d5-11ea-9b31-58727a4091b1.png">
yes so it pickup both on ground and stockpiles right now it will only pickup in green highlightet cell.
So inside a stockpile.

**Comment by nullre** [comment]
Would you like to set it in Def?
Or in-game? (building gizmo button etc.)

**Comment by zymex22** [comment]
xml are fine =)

**Comment by nullre** [comment]
added pickupFromGround option to SmartHopper.
https://github.com/nullre/Project-RimFactory-Revived/blob/97da2dc41c8660d356d24cd0c3f007e02c364b29/Defs/ThingDefs_Buildings/Buildings_Hoppers.xml#L91-L95

**Comment by zymex22** [comment]
this works thanks! :D
can PR and close =)
