### ISSUE TITLE
Wall puller

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#49]
it appears i can not use another texture for wall puller then the one item puller uses? 
if i try use graphic settings on it i will get errors.

and only works when its using that one from parant class

i was trying to use this one:
https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Textures/AutoMachineTool/Buildings/Puller/PullerWall0.png
https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Textures/AutoMachineTool/Buildings/Puller/PullerWall1.png

**Comment by nullre** [comment]
Must be:
Filename:

    PullerWall/Puller0.png
    PullerWall/Puller1.png

Building_AutoMachineTool_Puller_Wall graphicData

    <texPath>AutoMachineTool/Buildings/PullerWall</texPath>


Should I change it to the same method as workingGraphicData in Assembler?

**Comment by zymex22** [comment]
if that mean i can use `<graphicClass>Graphic_Multi</graphicClass>` like i can on assemblers.
That would be very good =) so i can add one for each rotation =) north, east, west, south =) instead of only single.

**Comment by nullre** [comment]
OK. I will change it to workingGraphicData.

**Comment by nullre** [comment]
Changed to get Working, Left, Right  GraphicData from ModExtension.
Textures/AutoMachineTool/Buildings/Puller directory is no longer used and is safe to delete.
Currently it is Graphic_Single, but I think it is possible to make it Multi.

https://github.com/nullre/Project-RimFactory-Revived/commit/3ccdbdcea1ff65d7a3dabb559445c4675745ae06#diff-e31f624a5ebec951af425cd9ea17a9bc

**Comment by zymex22** [comment]
seems to bee working can PR =)
