### ISSUE TITLE
My version

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#5]
I have edited and played alittle around with it, havent touched too much before it work easier to see whats new and old for my testers.
have changed alot of my own code so i put it in here combined with your edits.

also put a small edit i did on deepdrill  source (with help from rimworld forum)
\edits\Source\ProjectRimFactory\Industry
cant add it to your assemblies as i coundt get my compile to work from your source

Attached newest version im working on for next releasse.
[PRF_Core.zip](https://github.com/nullre/Project-RimFactory-Revived/files/4458965/PRF_Core.zip)

**Comment by nullre** [comment]
I synced your repository and integrated it into my branch.
Please check.
https://github.com/nullre/Project-RimFactory-Revived/tree/port_amt
