### ISSUE TITLE
Port wallLamp to PRF

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#50]
can you port Wall Lamp to PRF

**Comment by nullre** [comment]
I added wall light.
XML is sloppy.
https://github.com/nullre/Project-RimFactory-Revived/blob/ef9452bcfd8c443f7681056d7764fad57cb21096/Defs/ThingDefs_Buildings/Buildings_AutoMachineTool.xml#L283-L340

**Comment by zymex22** [comment]
working can PR
