### ISSUE TITLE
bug on recipe range

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#51]
got this comment:

> "There is definitely some problem with the Assembler and Adaptive Assembler both not reading recipes from Recipe Databases. I tested with several recipes from a Machining Table. Some worked, some did not. For example, Simple Helmet: yes, Frag Grenades: yes, Flak Vest: no, Revolver: no. It is not random. I put an Adaptive Assembler and an Assembler both next to the same database, and both were missing the same recipes. I created another database with the same recipes in a different order, and the same ones didn't work. It seems recipes from mods are more likely to work, but this is not universal."

i have tested it and seems to be right i cannot build flak vest but i can import it to db but assembler cant see it, even though its stored.

**Comment by zymex22** [comment]
hmm just tried remove:
```
      <li Class="ProjectRimFactory.SAL3.Things.CompProperties_RecipeImportRange">
        <range>3</range>
        <ghostColor>(0,1,1,1)</ghostColor>
      </li>
```
but bug is still present, is it something else in code being changed how assemblers read from recipe db ?

**Comment by nullre** [comment]
It does not appear depending on the SkillLevel condition.

    <skillLevel>20</skillLevel>

Add this and the recipe will appear.

When adding ArtSkillLevel, if SkillLevel is not set, all skill levels except Art are set to 0 and Art is set to 10.
This is the same state as before making the skill level settings.

Chronological order
- All skill levels except art are 0, art is 10, nothing skill level condition.(original prf)
- Added skill level setting, default  all skills 20. added skill level condition.(assember update part 1)
- Separated Art skill level setting, default  All skill levels except art are 0, art is 10. skill level condition is enable.(assember update part 2)

so, if skill level is not set, skill level is 0, so some recipes will not appear depending on the SkillLevel condition..

**Comment by nullre** [comment]
- Properly set the Skill Level for all Assembler. (your work in xml)
- Remove skill level condition. (Recipes appear that do not meet the skill level) (my work in C#)
- Set the skill level to 20 when not set. (my work in C#)

One of them is required.

**Comment by zymex22** [comment]
thanks i will close this and edit my version
