### ISSUE TITLE
Vacuum Hopper

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#52]
Hello everyone love new vacuum hopper function =)

but i got asked if i could make it use
- a gizmo button to toggle pickup from ground instead of mod settings
- and if it could use Power Range boost to make greater pickup range

**Comment by nullre** [comment]
implemented in fix_#52 branch.
power range settings.
https://github.com/nullre/Project-RimFactory-Revived/blob/b78847e47247ebc37fae7e7908c9bbbbfcc3c967/Defs/ThingDefs_Buildings/Buildings_Hoppers.xml#L75-L84

pickup from groud gizmo button texture is "SAL3/PickupFromGround".
copy form NewDisk.png for the time being. please change it.
https://github.com/nullre/Project-RimFactory-Revived/blob/b78847e47247ebc37fae7e7908c9bbbbfcc3c967/Source/ProjectRimFactory/SAL3/Things/Building_SmartHopper.cs#L211

**Comment by zymex22** [comment]
<img width="617" alt="error3" src="https://user-images.githubusercontent.com/41029070/81599878-29f73d80-93c9-11ea-9115-4af575219831.png">
getting this if pull from hopper to a storage crate.
no problem if from hopper to stockpile

https://gist.github.com/dc873dde8ee3f61bc2bac18277d83693

**Comment by nullre** [comment]
I fixed a bug. please check again.

**Comment by zymex22** [comment]
yes this works now can close and PR =) thank you
