### ISSUE TITLE
T3 miner exclude bug?

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#53]
Hello nobo been playing with make some tweaking.
but can't seem to get T3 to work?

```
      <li Class="ProjectRimFactory.Common.ModExtension_Miner">
        <excludeOres>
          <li>ComponentIndustrial</li>
          <li>Plasteel</li>
          <li>Jade</li>
        </excludeOres>
        <bonusYields Chance="0.01">
          <InsectJelly Weight="1" Count="30" />
        </bonusYields>
      </li>
```

if i use this only component gets excluded, jade and plasteel can still be mined.
If i remove component from list, plasteel and jade can also still be mined.

its only on T3 / NR miner, it works just fine on PRF one
am i doing something wrong?

<img width="465" alt="miner" src="https://user-images.githubusercontent.com/41029070/81781922-4397a280-94f9-11ea-838a-d4f8c9534042.png">

**Comment by nullre** [comment]
sorry. I fixed bug.
T3 miners are not limited to resourceRock, It also targets ores that can be dug with DeepDrill.
I have not excluded from DeepDrill ore list.

**Comment by zymex22** [comment]
that fixed the problem thanks :D can you PR?
