### ISSUE TITLE
Vanilla deep drill broke after RW update

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#54]
also got a few reports now that PRF seem to break Vanilla Deepcore drill's function after RW updated how Coredrill works, i have no idea why?

heres sone of them:
> Deep drill issue: the new patch expands the radius of the deep drill, which seems to be have broken something relating to the deep drill and PRF (this mod). What happens is that the deep drill only mines at the tile it's on, rather than over the expanded mining radius (basically not moving the tile it's mining within the radius). This causes the drill to mine an "empty" resource once the resource on it's tile is exhausted. This "empty" resource shows as a red "X" box that when inspected is an object in the ProjectRimFactory.Common.EffectThing class with id = PRFEffecterThing1486507.

> Deep drills are bugged since last rimworld update

> Deep drills stopped mining stone blocks after the last update. Not sure if the sam goes for metals.

I tested on our new version also seem to be true cant get that X he talks about, but it will empty one cell and just keep working but no output
picture had silver before but when depleted just say no ore under but still mine just dont get any ores.

<img width="582" alt="vanilla" src="https://user-images.githubusercontent.com/41029070/81810669-a140e480-9523-11ea-9b49-79f504feaa3b.png">

**Comment by nullre** [comment]
Thing was generated for Tick processing of Glower Pulse and Effecter.
Generated thing affects this issue.
Fixed to perform Tick process via MapComponentTick of MapComponent without generating Thing.

**Comment by zymex22** [comment]
wow that was fast adressed! :D just tested and it works can PR =)
