### ISSUE TITLE
refuelable comp on assembler and miners

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#55]
Hello can Refuelable comp be applied on Assembler and DeepQuarry.cs 
so it only use fuel when working on a bill and when digging with quarry

i tried with this, but it complain about DeepQuarry is Longtick and not Normal tick:

https://github.com/zymex22/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/Industry/Building_DeepQuarry.cs#L32

```
        public override void TickLong()
        {
            CompPowerTrader power=GetComp<CompPowerTrader>();
            CompRefuelable fuel=GetComp<CompRefuelable>();
            if ((power?.PowerOn!=false) && (fuel.HasFuel != false) && Rand.MTBEventOccurs(GetProduceMtbHours, GenDate.TicksPerHour, GenTicks.TickLongInterval))
            {
                GenerateChunk();
            }
        }
```

i use this in DEF:
```
      <li Class="CompProperties_Refuelable">
        <fuelConsumptionRate>80.0</fuelConsumptionRate>
        <fuelCapacity>50.0</fuelCapacity>
        <fuelFilter>
          <thingDefs>
            <li>WoodLog</li>
          </thingDefs>
        </fuelFilter>
        <showAllowAutoRefuelToggle>true</showAllowAutoRefuelToggle>
      </li>
```
if i dont add that into C# it dont uses any fuel when fueled as far i can tell
when i use: `<consumeFuelOnlyWhenUsed>true</consumeFuelOnlyWhenUsed>`
and if i remove it it will use fuel even when idle.
i want it to use fuel when working/on only =)

<img width="806" alt="fuel" src="https://user-images.githubusercontent.com/41029070/82029044-b1c59c00-9696-11ea-92ae-d2d7ce3cb220.png">

**Comment by zymex22** [comment]
hmm actually that might work on DeepQuarry without add it to C# since it work when on anyway so can just use flickable...

But can it be added to assemblers then? so my furnace only use fuel when actually smelting? =)

**Comment by zymex22** [comment]
what i need is:
- Be able to use Fueled comp too on deepquarry T1 use fuel when are turned on
- Be able to use Fueled on assemblers (for furnace T0)(only use fuel when doing a bill)

**Comment by nullre** [comment]
I changed TickerType to normal. and I made it work only at long intervals during tick processing.

https://github.com/nullre/Project-RimFactory-Revived/blob/15c04c98a69eb1c874e7d634cb745a7fdd5b1ce7/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L128

https://github.com/nullre/Project-RimFactory-Revived/blob/15c04c98a69eb1c874e7d634cb745a7fdd5b1ce7/Defs/ThingDefs_Buildings/Buildings_Industry.xml#L214

https://github.com/nullre/Project-RimFactory-Revived/blob/15c04c98a69eb1c874e7d634cb745a7fdd5b1ce7/Source/ProjectRimFactory/Industry/Building_DeepQuarry.cs#L32-L46

**Comment by zymex22** [comment]
that works perfectly :D better then what i managed to make with hints from LWM =) he was to tired to help me =)

**Comment by zymex22** [comment]
LWM asked if it wouldnt be a perfomance problem run it on Normal tick?

and asked if something like this wouldnt work:
```cs
        public override void TickLong()
        {
            CompPowerTrader power=GetComp<CompPowerTrader>();
            CompRefuelable fuel=GetComp<CompRefuelable>();
// Since we use a long tick, we have to manually consume fuel
//   used by a fueled autoquarry:
// (Note: set consumeFuelOnlyWhenUsed to true)
if (fuel!=null && (GetComp<CompFlickable>()?.SwitchIsOn!=false)) {
  fuel.ConsumeFuel(fuel.consumptionRatePerTick * 2000); //2000 ticks in a long tick
}
            if ((power?.PowerOn!=false) && (fuel?.HasFuel != false) && Rand.MTBEventOccurs(GetProduceMtbHours, GenDate.TicksPerHour, GenTicks.TickLongInterval))
            {
                GenerateChunk();
            }
        }
```
to still use LongTick instead of normal (for performance reasons he said)
and then he left, so couldnt ask for more, hes always so busy and on US time zone

also he asked if it wouldnt be smarter to have you as a collabator on PRF github so you could work directly in prf branches instead of seperat repo.
so i invited you to PRF if you want you can join that Repo, you are very welcome to, you are BIG part of this mod revival =)

**Comment by nullre** [comment]
What LWM is saying is correct. I think there are some performance issues.
However, I use TickNormal for two reasons.

1. As you say, TickLong gives a Config error. Since it seems CompRefuelable requires TickNomal, I thought it should process with TickNormal.
1. If set to TickLong, Fuel consumption interval will be opened. See below.

for example. set fuel to 0.1. See Inspect String `Fuel: xx / 50 (xx seconds)` in the lower left. and see interval until the fuel runs out.

**TickNormal:**
![GIF 2020-05-16 5-26-14](https://user-images.githubusercontent.com/29091845/82094494-269ce280-9738-11ea-869e-a497d6df958e.gif)

**TickLong (Triple speed from the middle):**
![GIF 2020-05-16 5-48-28](https://user-images.githubusercontent.com/29091845/82094970-0de0fc80-9739-11ea-8c0c-93d2634d4254.gif)

by the way, It might have been better to put these three lines in the If statement.

     var power = GetComp<CompPowerTrader>(); 
     var fuel = GetComp<CompRefuelable>(); 
     var flickable = GetComp<CompFlickable>(); 

> also he asked if it wouldnt be smarter to have you as a collabator on PRF github so you could work directly in prf branches instead of seperat repo.

What he says is right. but I am not good at English.
I cannot communicate with others in your repository.
I also need to understand the rules for creating/closing issues and branches in your repository (in English).
I know I am selfish, but please forgive me. I want to work following my rules in my repository.

**Comment by zymex22** [comment]
I think we should do whats best for performance but not affact function, so if Longtick can boost performance abit over normal.

then if posible i think we should use Longtick =)
what do you think?

yes no problem, it was just if it was easier for you, i also added you on steam workshop page so you can get credit for your good work =)
