### ISSUE TITLE
Request cultivator

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#7]
Can this **Building_DroneCultivator.cs**
ProjectRimFactory/CultivatorTools/Building_DroneCultivator.cs
https://github.com/nullre/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/CultivatorTools/Building_DroneCultivator.cs

have a output cell like old **Building_Cultivator.cs** had:
ProjectRimFactory/CultivatorTools/Building_Cultivator.cs
https://github.com/nullre/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/CultivatorTools/Building_Cultivator.cs

if its something you know how to make

**Comment by nullre** [comment]
if add haul jobs, drones will haul harvested plants. maybe.

**Comment by zymex22** [comment]
Seems to work, sometimes hauler take harvest to near storage though.

- also it will only do center north, south, west, east, outside growzone.
can it take all fields around growzone instead of only center or too hard?
