### ISSUE TITLE
Request Storage

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#8]
can this: **Building_MassStorageUnitPowered.cs**
https://github.com/nullre/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/Storage/Building_MassStorageUnitPowered.cs

be able to set a max limit stored

maybe this can be used to set limit?
https://github.com/nullre/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/Storage/Editables/DefModExtension_Crate.cs
_Source/ProjectRimFactory/Storage/Editables/DefModExtension_Crate.cs_

**Comment by nullre** [comment]
Building_MassStorageUnitPowered.cs

    public override bool CanReceiveIO => base.CanReceiveIO && GetComp<CompPowerTrader>().PowerOn;

change

    public override bool CanStoreMoreItems => base.CanReceiveIO && GetComp<CompPowerTrader>().PowerOn && Position.GetThingList(Map).Count(t => t.def.category == ThingCategory.Item) < (Extension.limit - def.Size.Area + 1);
    public DefModExtension_Crate Extension => def.GetModExtension<DefModExtension_Crate>();


Maybe it will behave like a crate.

**Comment by nullre** [comment]
sorry.mistake.

    public override bool CanStoreMoreItems => GetComp<CompPowerTrader>().PowerOn;

↓

    public override bool CanStoreMoreItems => GetComp<CompPowerTrader>().PowerOn && Position.GetThingList(Map).Count(t => t.def.category == ThingCategory.Item) < (Extension.limit - def.Size.Area + 1);
    public DefModExtension_Crate Extension => def.GetModExtension<DefModExtension_Crate>();

**Comment by nullre** [comment]
mistake commit message. ignore 30820c9.

**Comment by nullre** [comment]
implemented in fix_#8 branch. please check it out.

**Comment by zymex22** [comment]
i will have to test further to see if this work i will come back later with more info
