### ISSUE TITLE
I/O port

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#9]
Can this: Source/ProjectRimFactory/Storage/Building_StorageUnitIOPort.cs

https://github.com/nullre/Project-RimFactory-Revived/blob/master/Source/ProjectRimFactory/Storage/Building_StorageUnitIOPort.cs

be made so change color/texture when set to input / output so its visual what its on? like when puller work change texture ?

**Comment by nullre** [comment]
Set drawerType to RealtimeOnly on xml.
override Graphic property, return colored Graphic on C# code.

**Comment by zymex22** [comment]
can it use mask to color, so mask change color? or do it need 2 textures like texture0 and texture1?

**Comment by zymex22** [comment]
Work, seems good =)
